// <auto-generated />
using System;
using Final_Project_2._1.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_Project_2._1.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20221027224031_DbVersion1")]
    partial class DbVersion1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Final_Project_2._1.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("codPostal")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("localidade")
                        .HasColumnType("longtext");

                    b.Property<string>("morada")
                        .HasColumnType("longtext");

                    b.Property<int>("nif")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.Property<float>("saldoDisp")
                        .HasColumnType("float");

                    b.Property<int>("telefone")
                        .HasColumnType("int");

                    b.Property<DateTime>("validade")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
